### PR TITLE
nitpicks

### PR DESCRIPTION
**Pull request by gnzlbg**

### CODE REVIEW

**Comment by lu-zero** [comment]
I have a bit of conflict between what I have in the ppc64 and the thing I have on the arm box... I'd try to conciliate those and merge in your changes.

**Comment by lu-zero** [comment]
I should have them addressed in a way or another, tell me if you are happy with what I have now.

**Comment by gnzlbg** [comment]
Everything looks great, thanks! The only thing that seems to be missing are the tests for Power5 that check that altivec is not detected there.

**Comment by lu-zero** [comment]
Oh, right, let me bring it up.

**Pull request closed without merging**
